var countries = {
	"AAL":"Aalborg (AAL)",
	"AAR":"Aarhus (AAR)",
	"YXX":"Abbotsford (YXX)",
	"ABZ":"Aberdeen (ABZ)",
	"ABJ":"Abidjan (ABJ)",
	"AUH":"Abu Dhabi (AUH)",
	"ABV":"Abuja (ABV)",
	"ACA":"Acapulco (ACA)",
	"ACC":"Accra (ACC)",
	"ADD":"Addis Ababa (ADD)",
	"ADL":"Adelaida (ADL)",
	"AGU":"AguasCalientes (AGU)",
	"AJA":"Ajaccio (AJA)",
	"CAK":"Akron (CAK)",
	"ABQ":"Albuquerque (ABQ)",
	"ALY":"Alexandria (ALY)",
	"AHO":"Alghero (AHO)",
	"ALC":"Alicante (ALC)",
	"LEI":"Almería (LEI)",
	"AMM":"Amã (AMM)",
	"AMS":"Amsterdã (AMS)",
	"ESB":"Ancara (ESB)",
	"ANC":"Anchorage (ANC)",
	"AOI":"Ancona (AOI)",
	"AAE":"Annaba-Rabah (AAE)",
	"AYT":"Antália (AYT)",
	"TNR":"Antananarivo (TNR)",
	"ANF":"Antofagasta (ANF)",
	"ANR":"Antuérpia (ANR)",
	"APO":"Apartadó (APO)",
	"AJU":"Aracaju (AJU)",
	"AUC":"Arauca (AUC)",
	"AQP":"Arequipa (AQP)",
	"ALG":"Argel (ALG)",
	"ARI":"Arica (ARI)",
	"AXM":"Armenia (AXM)",
	"AVL":"Asheville (AVL)",
	"ASU":"Assunção (ASU)",
	"ASW":"Aswan (ASW)",
	"ATH":"Atenas (ATH)",
	"ATL":"Atlanta (ATL)",
	"ACY":"Atlantic City (ACY)",
	"AKL":"Auckland (AKL)",
	"AUS":"Austin (AUS)",
	"FKB":"Baden-Baden (FKB)",
	"SDA":"Bagdad (SDA)",
	"BHI":"Bahía Blanca (BHI)",
	"BAH":"Bahréin (BAH)",
	"GYD":"Baku (GYD)",
	"BWI":"Baltimore (BWI)",
	"BLR":"Bangalore (BLR)",
	"BKK":"Banguecoque (BKK)",
	"BCN":"Barcelona (BCN)",
	"BLA":"Barcelona (BLA)",
	"BRI":"Bari (BRI)",
	"BRC":"Bariloche (BRC)",
	"BRM":"Barquisimeto (BRM)",
	"EJA":"Barrancabermeja (EJA)",
	"BAQ":"Barranquilla (BAQ)",
	"BSL":"Basileia-Mulhouse (BSL)",
	"BVA":"Beauvais Tillé (BVA)",
	"BEY":"Beirute (BEY)",
	"BEL":"Belem (BEL)",
	"BFS":"Belfast (BFS)",
	"BHD":"Belfast (BHD)",
	"BEG":"Belgrado Nikola Tesla (BEG)",
	"CNF":"Belo Horizonte (CNF)",
	"PLU":"Belo Horizonte (PLU)",
	"TODOS":"Belo Horizonte (TODOS)",
	"BGY":"Bergamo (BGY)",
	"BGO":"Bergen (BGO)",
	"BER":"Berlim (BER)",
	"SXF":"Berlim (SXF)",
	"TXL":"Berlim (TXL)",
	"BRN":"Berna (BRN)",
	"BIQ":"Biarritz-Anglet-Bayonne (BIQ)",
	"BIO":"Bilbao (BIO)",
	"BLL":"Billund (BLL)",
	"BHX":"Birmingham (BHX)",
	"BHM":"Birmingham (BHM)",
	"BIS":"Bismarck (BIS)",
	"BLK":"Blackpool (BLK)",
	"BFN":"Bloemfontein (BFN)",
	"BVB":"Boa Vista (BVB)",
	"BOO":"Bodø (BOO)",
	"BOG":"Bogotá (BOG)",
	"BOI":"Boise (BOI)",
	"BLQ":"Bolonha (BLQ)",
	"BOM":"Bombaim (BOM)",
	"BOD":"Bordéus (BOD)",
	"RNN":"Bornholm (RNN)",
	"BOS":"Boston (BOS)",
	"BOH":"Bournemouth (BOH)",
	"BWK":"Brac (BWK)",
	"BDL":"Bradley (BDL)",
	"BSB":"Brasilia (BSB)",
	"BTS":"Bratislava (BTS)",
	"BZV":"Brazzaville (BZV)",
	"BRE":"Bremen (BRE)",
	"WRO":"Breslavia (WRO)",
	"BES":"Brest Bretagne (BES)",
	"BGI":"Bridgetown (BGI)",
	"BDS":"Brindisi (BDS)",
	"BNE":"Brisbane (BNE)",
	"BRS":"Bristol (BRS)",
	"BRQ":"Brno (BRQ)",
	"BRU":"Bruxelas (BRU)",
	"CRL":"Bruxelas (CRL)",
	"BGA":"Bucaramanga (BGA)",
	"BPU":"Bucareste (BBU)",
	"OTP":"Bucareste (OTP)",
	"BUD":"Budapeste (BUD)",
	"AEP":"Buenos Aires (AEP)",
	"EZE":"Buenos Aires (EZE)",
	"BUF":"Buffalo (BUF)",
	"BUR":"Burbank (BUR)",
	"BOJ":"Burgas (BOJ)",
	"BTV":"Burlington (BTV)",
	"PUS":"Busán (PUS)",
	"BJM":"Buyumbura (BJM)",
	"COR":"Córdoba (COR)",
	"CAG":"Cagliari (CAG)",
	"CNS":"Cairns (CNS)",
	"CAI":"Cairo (CAI)",
	"CJC":"Calama (CJC)",
	"CCU":"Calcutá (CCU)",
	"YYC":"Calgary (YYC)",
	"CLO":"Cali (CLO)",
	"CBR":"Camberra (CBR)",
	"CPE":"Campeche (CPE)",
	"VCP":"Campinas (VCP)",
	"CGR":"Campo Grande (CGR)",
	"CUN":"Cancun (CUN)",
	"CCS":"Caracas (CCS)",
	"CWL":"Cardiff (CWL)",
	"CTG":"Cartagena de Indias (CTG)",
	"CMN":"Casablanca (CMN)",
	"CTA":"Catânia (CTA)",
	"CTC":"Catamarca (CTC)",
	"CHQ":"Chania (CHQ)",
	"CPC":"Chapelco (CPC)",
	"CHS":"Charleston (CHS)",
	"NOC":"Charleston (NOC)",
	"CLT":"Charlotte (CLT)",
	"MAA":"Chennai (MAA)",
	"CTM":"Chetumal (CTM)",
	"CNX":"Chiang Mai (CNX)",
	"MDW":"Chicago (MDW)",
	"ORD":"Chicago (ORD)",
	"CIX":"Chiclayo (CIX)",
	"CUU":"Chihuahua (CUU)",
	"CHC":"Christchurch (CHC)",
	"CPT":"Cidade do Cabo (CPT)",
	"NLD":"Cidade do Mexico (NLD)",
	"PXM":"Cidade do Mexico (PXM)",
	"HMO":"Cidade do Mexico (HMO)",
	"MEX":"Cidade do Mexico (MEX)",
	"CVG":"Cincinnati (CVG)",
	"GUA":"Ciudad de Guatemala (GUA)",
	"PTY":"Ciudad de Panamá (PTY)",
	"CME":"Ciudad del Carmen (CME)",
	"CJS":"Ciudad Juarez (CJS)",
	"CEN":"Ciudad Obregon (CEN)",
	"CVM":"Ciudad Victoria (CVM)",
	"CFE":"Clermont-Ferrand (CFE)",
	"CLE":"Cleveland (CLE)",
	"CLJ":"Cluj-Napoca (CLJ)",
	"CBB":"Cochabamba (CBB)",
	"CGN":"Colónia/Bonn (CGN)",
	"CLQ":"Colima (CLQ)",
	"CMB":"Colombo (CMB)",
	"COS":"Colorado Springs (COS)",
	"CAE":"Columbia (CAE)",
	"CHM":"Columbus (CMH)",
	"CRD":"Comodoro Rivadavia (CRD)",
	"CCP":"Concepción (CCP)",
	"CPH":"Copenhaga (CPH)",
	"CFU":"Corfu (CFU)",
	"ORK":"Cork (ORK)",
	"LCG":"Corunha (LCG)",
	"COO":"Cotonu (COO)",
	"CZM":"Cozumel (CZM)",
	"KRK":"Cracóvia (KRK)",
	"CUC":"Cucuta (CUC)",
	"CUE":"Cuenca (CUE)",
	"CGB":"Cuiabá (CGB)",
	"CUL":"Culiacan (CUL)",
	"CWB":"Curitiba (CWB)",
	"CUZ":"Cusco (CUZ)",
	"DUS":"Düsseldorf (DUS)",
	"DAC":"Dacca (DAC)",
	"DKR":"Dakar (DKR)",
	"DLM":"Dalaman (DLM)",
	"DFW":"Dallas (DFW)",
	"DAM":"Damasco (DAM)",
	"DRW":"Darwin (DRW)",
	"DAY":"Dayton (DAY)",
	"DAB":"Daytona Beach (DAB)",
	"DEB":"Debrecen (DEB)",
	"DPS":"Denpasar (DPS)",
	"DEN":"Denver (DEN)",
	"LDY":"Derry (LDY)",
	"DSM":"Des Moines (DSM)",
	"DTW":"Detroit (DTW)",
	"DOH":"Doha (DOH)",
	"DSA":"Doncaster-Sheffield (DSA)",
	"DTM":"Dortmund (DTM)",
	"DLA":"Douala (DLA)",
	"DRS":"Dresde (DRS)",
	"DXB":"Dubai (DXB)",
	"DUB":"Dublin (DUB)",
	"DBV":"Dubrovnik (DBV)",
	"DUD":"Dunedin (DUD)",
	"DGO":"Durango (DGO)",
	"DUR":"Durban (DUR)",
	"MME":"Durham Tees Valley (MME)",
	"EGE":"Eagle (EGE)",
	"ELS":"East London (ELS)",
	"EMA":"East Midlands (EMA)",
	"SVX":"Ecaterinburgo (SVX)",
	"EDI":"Edimburgo (EDI)",
	"YEG":"Edmonton (YEG)",
	"EIN":"Eindhoven (EIN)",
	"FTE":"El Calafate (FTE)",
	"VDE":"El Hierro (VDE)",
	"ELP":"El Paso (ELP)",
	"ECN":"Ercan (ECN)",
	"ERI":"Erie (ERI)",
	"EBJ":"Esbjerg (EBJ)",
	"SID":"Espargos (SID)",
	"ARN":"Estocolmo (ARN)",
	"BMA":"Estocolmo (BMA)",
	"NYO":"Estocolmo (NYO)",
	"SXB":"Estrasburgo (SXB)",
	"EUG":"Eugene (EUG)",
	"EXT":"Exeter (EXT)",
	"EXT":"Fargo (FAR)",
	"EXT":"Faro (FAO)",
	"FAY":"Fayetteville (FAY)",
	"PHL":"Filadelfia (PHL)",
	"FNT":"	Flint (FNT)",
	"FLN":"	Florença (FLR)",
	"FLN":"Florianopolis (FLN)",
	"FRL":"Forli (FRL)",
	"FMA":"Formosa (FMA)",
	"FLL":"Fort Lauderdale (FLL)",
	"RSW":"Fort Myers (RSW)",
	"FOR":"Fortaleza (FOR)",
	"IGU":"Foz de Iguaçu (IGU)",
	"FRA":"Frankfurt (FRA)",
	"HHN":"Frankfurt (HHN)",
	"FAT":"Fresno (FAT)",
	"FUE":"Fuerteventura (FUE)",
	"GOA":"Génova (GOA)",
	"GBE":"Gaborone (GBE)",
	"GDN":"Gdansk (GDN)",
	"GVA":"Genebra (GVA)",
	"GPO":"General Pico (GPO)",
	"GRJ":"George (GRJ)",
	"GRO":"Girona (GRO)",
	"GLA":"Glasgow (GLA)",
	"PIK":"Glasgow (PIK)",
	"GYN":"Goiânia (GYN)",
	"GOT":"Gotemburgo (GOT)",
	"GSE":"Gotemburgo (GSE)",
	"LPA":"Gran Canária (LPA)",
	"GRX":"Granada-Jaén (GRX)",
	"GFK":"Grand Forks (GFK)",
	"GRZ":"Graz (GRZ)",
	"GSO":"Greensboro (GSO)",
	"GSP":"Greenville-Spartanburg (GSP)",
	"GNB":"Grenoble-Isere (GNB)",
	"GRQ":"Groningen (GRQ)",
	"GDL":"Guadalajara (GDL)",
	"GYE":"Guaiaquil (GYE)",
	"CAN":"Guangzhou (CAN)",
	"GYM":"Guaymas (GYM)",
	"GCI":"Guernsey (GCI)",
	"YHZ":"Halifax (YHZ)",
	"HAM":"Hamburgo (HAM)",
	"HAN":"Hanoi (HAN)",
	"HAJ":"Hanover (HAJ)",
	"MDT":"Harrisburg (MDT)",
	"EVE":"Harstad/Narvik (EVE)",
	"HAV":"Havana (HAV)",
	"HEL":"Helsinque (HEL)",
	"HER":"Heraklion (HER)",
	"JBQ":"Higüero (JBQ)",
	"SGN":"Ho Chi Minh (SGN)",
	"HKG":"Hong Kong (HKG)",
	"HNL":"Honolulu (HNL)",
	"HOR":"Horta (HOR)",
	"HOU":"Houston (HOU)",
	"IAH":"Houston (IAH)",
	"HUX":"Huatulco (HUX)",
	"HSK":"Huesca-Pirinéus(HSK)",
	"HUY":"Humberside (HUY)",
	"HSV":"Huntsville (HSV)",
	"HRG":"Hurgadah (HRG)",
	"IAS":"Iasi (IAS)",
	"IBE":"Ibagué (IBE)",
	"IBZ":"Ibiza (IBZ)",
	"FLW":"Ilha das Flores (FLW)",
	"KGS":"Ilha de Kos (KGS)",
	"IOM":"Ilha de Man (IOM)",
	"IPC":"Ilha de Páscoa (IPC)",
	"ADZ":"Ilha de San Andrés (ADZ)",
	"PMV":"Ilha Margarita (PMV)",
	"IOS":"Ilhéus (IOS)",
	"IMP":"Imperatriz (IMP)",
	"IND":"Indianapolis (IND)",
	"INN":"Innsbruck (INN)",
	"INV":"Inverness (INV)",
	"IQQ":"Iquique (IQQ)",
	"IQT":"Iquitos (IQT)",
	"IKT":"Irkutsk (IKT)",
	"ISP":"Islip (ISP)",
	"IST":"Istambul (IST)",
	"SAW":"Istambul (SAW)",
	"NVT":"Itajai (NVT)",
	"IVL":"Ivalo (IVL)",
	"ADB":"Izmir (ADB)",
	"JAX":"Jacksonville (JAX)",
	"OAJ":"Jacksonville (OAJ)",
	"KRT":"Jartum (KRT)",
	"CJU":"Jeju (CJU)",
	"XRY":"Jerez (XRY)",
	"JER":"Jersey (JER)",
	"JPA":"João Pessoa (JPA)",
	"JNB":"Joanesburgo (JNB)",
	"JOI":"Joinville (JOI)",
	"OGG":"Kahului (OGG)",
	"MCI":"Kansas City (MCI)",
	"KHI":"Karachi (KHI)",
	"KLV":"Karlovy Vary (KLV)",
	"KRP":"Karup (KRP)",
	"KTW":"Katowice (KTW)",
	"KUN":"Kaunas (KUN)",
	"KEF":"Keflavík (KEF)",
	"YLW":"Kelowna (YLW)",
	"IEV":"Kiev (IEV)",
	"KBP":"Kiev (KBP)",
	"KIM":"Kimberley (KIM)",
	"KIN":"Kingston (KIN)",
	"FIH":"Kinshasa (FIH)",
	"KLU":"Klagenfurt (KLU)",
	"KSC":"Kosice (KSC)",
	"KRS":"Kristiansand (KRS)",
	"KUL":"Kuala Lumpur (KUL)",
	"KWI":"Kuwait (KWI)",
	"LCE":"La Ceiba (LCE)",
	"SPC":"La Palma (SPC)",
	"LPB":"La Paz (LPB)",
	"LAP":"La Paz (LAP)",
	"IRJ":"La Rioja (IRJ)",
	"ILD":"Lérida (ILD)",
	"LOS":"Lagos (LOS)",
	"TER":"Lajes (TER)",
	"SUF":"Lamezia Terme (SUF)",
	"ACE":"Lanzarote (ACE)",
	"LCA":"Larnaca (LCA)",
	"LAS":"Las Vegas (LAS)",
	"LAW":"Lawton (LAW)",
	"LEN":"León (LEN)",
	"LBA":"Leeds Bradford (LBA)",
	"LEJ":"Leipzig/Halle (LEJ)",
	"LEY":"Lelystad (LEY)",
	"BJX":"Leon (BJX)",
	"LET":"Leticia (LET)",
	"LEX":"Lexington (LEX)",
	"LBV":"Libreville (LBV)",
	"LGG":"Lieja (LGG)",
	"LPX":"Liepaja (LPX)",
	"LIL":"Lille (LIL)",
	"LIM":"Lima (LIM)",
	"LNZ":"Linz (LNZ)",
	"LIS":"Lisboa (LIS)",
	"LIT":"Little Rock (LIT)",
	"LJU":"Liubliana (LJU)",
	"LPL":"Liverpool (LPL)",
	"LCY":"Londres (LCY)",
	"LGW":"Londres (LGW)",
	"LHR":"Londres (LHR)",
	"LTN":"Londres (LTN)",
	"SEN":"Londres (SEN)",
	"STN":"Londres (STN)",
	"YXU":"Londres (YXU)",
	"LDB":"Londrina (LDB)",
	"LGB":"Long Beach (LGB)",
	"LTO":"Loreto (LTO)",
	"LAX":"Los Angeles (LAX)",
	"LMM":"Los Mochis (LMM)",
	"SDF":"Louisville (SDF)",
	"LAD":"Luanda (LAD)",
	"SDD":"Lubango (SDD)",
	"LUG":"Lugano (LUG)",
	"LLA":"Luleå (LLA)",
	"LUX":"Luxemburgo (LUX)",
	"LXR":"Luxor (LXR)",
	"LYS":"Lyon (LYS)",
	"AGP":"Málaga (AGP)",
	"FMO":"Münster/Osnabrück (FMO)",
	"MST":"Maastricht-Aachen (MST)",
	"MEA":"Macaé (MEA)",
	"MCP":"Macapá (MCP)",
	"MFM":"Macau (MFM)",
	"MCZ":"Maceio (MCZ)",
	"FNC":"Madeira (FNC)",
	"MAD":"Madrid (MAD)",
	"MCJ":"Maicao (MCJ)",
	"MLE":"Malé (MLE)",
	"LGS":"Malargüe (LGS)",
	"MMX":"Malmö (MMX)",
	"MLA":"Malta (MLA)",
	"MGA":"Managua (MGA)",
	"MAO":"Manaus (MAO)",
	"MAN":"Manchester (MAN)",
	"MHT":"Manchester (MHT)",
	"MLN":"Manila (MNL)",
	"MZL":"Manizales (MZL)",
	"ZLO":"Manzanillo (ZLO)",
	"MJV":"Múrcia (MJV)",
	"MDQ":"Mar del Plata (MDQ)",
	"MAR":"Maracaibo (MAR)",
	"MBX":"Maribor (MBX)",
	"MHQ":"Mariehamn (MHQ)",
	"RAK":"Marrakech (RAK)",
	"MRS":"Marselha (MRS)",
	"MCT":"Mascate (MCT)",
	"MAM":"Matamoros (MAM)",
	"MZT":"Mazatlan (MZT)",
	"EOH":"Medellín (EOH)",
	"MDE":"Medellín (MDE)",
	"MFR":"Medford (MFR)",
	"MEL":"Melbourne (MEL)",
	"MLN":"Melilla (MLN)",
	"MEM":"Memphis (MEM)",
	"MDZ":"Mendoza (MDZ)",
	"MAH":"Menorca (MAH)",
	"MID":"Merida (MID)",
	"ETZ":"Metz-Nancy-Lorraine (ETZ)",
	"MXL":"Mexicali (MXL)",
	"MIA":"Miami (MIA)",
	"LIN":"Milão (LIN)",
	"MXP":"Milão (MXP)",
	"MKE":"Milwaukee (MKE)",
	"MTT":"Minatitlan (MTT)",
	"MSP":"Minneapolis (MSP)",
	"MOT":"Minot (MOT)",
	"MSQ":"Minsk (MSQ)",
	"MIR":"Monastir (MIR)",
	"YQM":"Moncton (YQM)",
	"MBJ":"Montego Bay (MBJ)",
	"MTR":"Montería (MTR)",
	"MTY":"Monterrey (MTY)",
	"MVD":"Montevideu (MVD)",
	"MPL":"Montpellier (MPL)",
	"YHU":"Montreal (YHU)",
	"YUL":"Montreal (YUL)",
	"MLM":"Morelia (MLM)",
	"DME":"Moscovo (DME)",
	"SVO":"Moscovo (SVO)",
	"VKO":"Moscovo (VKO)",
	"MUC":"Munique (MUC)",
	"JKM":"Mykonos (JMK)",
	"MYR":"Myrtle Beach (MYR)",
	"FNI":"Nîmes (FNI)",
	"NGO":"Nagoia (NGO)",
	"NBO":"Nairobi (NBO)",
	"NTE":"Nantes (NTE)",
	"NAP":"Napoles (NAP)",
	"BNA":"Nashville (BNA)",
	"NAS":"Nassau (NAS)",
	"NAT":"Natal (NAT)",
	"NAV":"Navegantes (NAV)",
	"NVA":"Neiva (NVA)",
	"NQN":"Neuquén (NQN)",
	"EWN":"New Bern (EWN)",
	"HVN":"New Haven (HVN)",
	"NCL":"Newcastle (NCL)",
	"NQY":"Newquay (NQY)",
	"NCE":"Nice (NCE)",
	"NWI":"Norwich (NWI)",
	"DEL":"Nova Deli (DEL)",
	"EWR":"Nova Jersey (EWR)",
	"MSY":"Nova Orleans (MSY)",
	"JFK":"Nova York (JFK)",
	"LGA":"Nova York (LGA)",
	"NUE":"Nuremberg (NUE)",
	"ODS":"Odessa (ODS)",
	"OKC":"Oklahoma City (OKC)",
	"OLB":"Olbia (OLB)",
	"OMA":"Omaha (OMA)",
	"ONT":"Ontario (ONT)",
	"AUA":"Oranjestad (AUA)",
	"MCO":"Orlando (MCO)",
	"KIX":"Osaka (KIX)",
	"OSI":"Osijek (OSI)",
	"OSL":"Oslo (OSL)",
	"OST":"Ostende-Bruges (OST)",
	"OSR":"Ostrava (OSR)",
	"YOW":"Ottawa (YOW)",
	"OUA":"Ouagadougou (OUA)",
	"OUL":"Oulu (OUL)",
	"OVD":"Oviedo-Gijon (OVD)",
	"PFO":"Pafos (PFO)",
	"PLQ":"Palanga (PLQ)",
	"PMO":"Palermo (PMO)",
	"PSP":"Palm Springs (PSP)",
	"PMI":"Palma de Mallorca (PMI)",
	"PMW":"Palmas (PMW)",
	"PNA":"Pamplona (PNA)",
	"PPT":"Papeete (PPT)",
	"PRA":"Paraná (PRA)",
	"PED":"Pardubice (PED)",
	"CDG":"Paris (CDG)",
	"ORY":"Paris (ORY)",
	"PMF":"Parma (PMF)",
	"PUF":"Pau-Pirineos (PUF)",
	"PEN":"Penang (PEN)",
	"PEK":"Pequim (PEK)",
	"PEI":"Pereira (PEI)",
	"PER":"Perth (PER)",
	"PNZ":"Petrolina (PNZ)",
	"PHZ":"Phoenix (PHX)",
	"HKT":"Phuket (HKT)",
	"PZY":"Piestany (PZY)",
	"NTY":"Pilanesberg (NTY)",
	"PSA":"Pisa (PSA)",
	"PIT":"Pittsburgh (PIT)",
	"PIU":"Piura (PIU)",
	"PDV":"Plovdiv (PDV)",
	"PDL":"Ponta Delgada (PDL)",
	"PPN":"Popayán (PPN)",
	"TAT":"Poprad-Tatry (TAT)",
	"PLZ":"Port Elizabeth (PLZ)",
	"MRU":"Port Louis (MRU)",
	"PDX":"Portland (PDX)",
	"OPO":"Porto (OPO)",
	"POA":"Porto Alegre (POA)",
	"POS":"Porto de Espanha (POS)",
	"PVH":"Porto Velho (PVH)",
	"POW":"Portoroz (POW)",
	"PSS":"Posadas (PSS)",
	"PAZ":"Poza Rica (PAZ)",
	"POZ":"Poznan (POZ)",
	"PRG":"Praga (PRG)",
	"PRN":"Pristina Kosovo (PRN)",
	"PVD":"Providence (PVD)",
	"PBC":"Puebla (PBC)",
	"PUU":"Puerto Asís (PUU)",
	"IGR":"Puerto Iguazú (IGR)",
	"PMY":"Puerto Madryn (PMY)",
	"PMC":"Puerto Montt (PMC)",
	"POP":"Puerto Plata (POP)",
	"PVR":"Puerto Vallarta (PVR)",
	"PUY":"Pula (PUY)",
	"PUQ":"Punta Arenas (PUQ)",
	"PUJ":"Punta Cana (PUJ)",
	"PDP":"Punta del Este (PDP)",
	"YQB":"Quebec (YQB)",
	"ZQN":"Queenstown (ZQN)",
	"QRO":"Queretaro (QRO)",
	"UIB":"Quibdó (UIB)",
	"UIO":"Quito (UIO)",
	"RCU":"Río Cuarto (RCU)",
	"RGL":"Río Gallegos (RGL)",
	"RBA":"Rabat (RBA)",
	"RDU":"Raleigh (RDU)",
	"REC":"Recife (REC)",
	"RDM":"Redmond (RDM)",
	"REG":"Reggio Calabria (REG)",
	"RKV":"Reiquiavique (RKV)",
	"RNS":"Rennes (RNS)",
	"RNO":"Reno (RNO)",
	"RES":"Resistencia (RES)",
	"RIC":"Richmond (RIC)",
	"RIX":"Riga (RIX)",
	"RJK":"Rijeka (RJK)",
	"RBR":"Rio Branco (RBR)",
	"GIG":"Rio de Janeiro (GIG)",
	"SDU":"Rio de Janeiro (SDU)",
	"RGA":"Rio Grande (RGA)",
	"RUH":"Riyadh (RUH)",
	"RHO":"Rodes (RHO)",
	"RDZ":"Rodez-Marcillac (RDZ)",
	"CIA":"Roma (CIA)",
	"FCO":"Roma (FCO)",
	"ROS":"Rosario (ROS)",
	"RTM":"Roterdão (RTM)",
	"RVN":"Rovaniemi (RVN)",
	"SOB":"Sármellék (SOB)",
	"SLZ":"São Luís (SLZ)",
	"SAO":"São Paulo (TODOS)",
	"CHG":"São Paulo (CGH)",
	"GRU":"São Paulo (GRU)",
	"LED":"São Petersburgo (LED)",
	"EAS":"São Sebastião (EAS)",
	"SCN":"Saarbrücken (SCN)",
	"SMF":"Sacramento (SMF)",
	"SLC":"Salt Lake City (SLC)",
	"SLA":"Salta (SLA)",
	"SSA":"Salvador (SSA)",
	"SZG":"Salzburgo (SZG)",
	"SAT":"San Antonio (SAT)",
	"SVZ":"San Antonio del Táchira (SVZ)",
	"SAN":"San Diego (SAN)",
	"SFO":"San Francisco (SFO)",
	"SJD":"San José del Cabo (SJD)",
	"SJO":"San Jose (SJO)",
	"SJC":"San Jose (SJC)",
	"UAQ":"San Juan (UAQ)",
	"SJU":"San Juan (SJU)",
	"PSO":"San Juan de Pasto (PSO)",
	"LUQ":"San Luis (LUQ)",
	"SLP":"San Luis de Potosi (SLP)",
	"AFA":"San Rafael (AFA)",
	"SAL":"San Salvador (SAL)",
	"JUJ":"San Salvador de Jujuy (JUJ)",
	"TRF":"Sandefjord (TRF)",
	"SNA":"Santa Ana (SNA)",
	"SBA":"Santa Barbara (SBA)",
	"VVI":"Santa Cruz de la Sierra (VVI)",
	"SFN":"Santa Fe (SFN)",
	"SMA":"Santa Maria (SMA)",
	"SMR":"Santa Marta (SMR)",
	"RSA":"Santa Rosa La Pampa (RSA)",
	"SDR":"Santander (SDR)",
	"STM":"Santarém (STM)",
	"SCL":"Santiago de Chile (SCL)",
	"SCQ":"Santiago de Compostela (SCQ)",
	"STI":"Santiago de los Caballeros (STI)",
	"SDE":"Santiago del Estero (SDE)",
	"SDQ":"Santo Domingo (SDQ)",
	"ZAZ":"Saragoça (ZAZ)",
	"SRQ":"Sarasota (SRQ)",
	"YXE":"Saskatoon (YXE)",
	"TAB":"Scarborough (TAB)",
	"SEA":"Seattle (SEA)",
	"GMP":"Seul (GMP)",
	"ICN":"Seul (ICN)",
	"SVQ":"Sevilha (SVQ)",
	"SNN":"Shannon (SNN)",
	"SSH":"Sharm el-Sheikh (SSH)",
	"SIN":"Singapura (SIN)",
	"FSD":"Sioux Falls (FSD)",
	"SLD":"Sliac (SLD)",
	"SOF":"Sofía (SOF)",
	"SGD":"Sonderborg (SGD)",
	"SOU":"Southampton (SOU)",
	"SPU":"Split (SPU)",
	"ANU":"St John's (ANU)",
	"YYT":"St John's (YYT)",
	"STL":"St. Louis (STL)",
	"SCE":"State College (SCE)",
	"SVG":"Stavanger (SVG)",
	"STR":"Stuttgart (STR)",
	"SUB":"Surabaya (SUB)",
	"SYD":"Sydney (SYD)",
	"SZZ":"Szczecin (SZZ)",
	"HND":"Tóquio (HND)",
	"NRT":"Tóquio (NRT)",
	"TPE":"Taipei (TPE)",
	"TLL":"Tallinn (TLL)",
	"TPA":"Tampa (TPA)",
	"TMP":"Tampere-Pirkkala (TMP)",
	"TAM":"Tampico (TAM)",
	"TNG":"Tanger (TNG)",
	"TAP":"Tapachula (TAP)",
	"LDE":"Tarbes-Lourdes-Pirineos (LDE)",
	"REU":"Tarragona-Reus (REU)",
	"IKA":"Teerão (IKA)",
	"TGU":"Tegucigalpa (TGU)",
	"TVL":"Tel Aviv (TLV)",
	"TFN":"Tenerife Norte (TFN)",
	"TFS":"Tenerife Sul (TFS)",
	"TPQ":"Tepic (TPQ)",
	"THE":"Teresina (THE)",
	"SKG":"Tessalónica (SKG)",
	"TEB":"Teterboro (TEB)",
	"TBS":"Tiflis (TBS)",
	"TIJ":"Tijuana (TIJ)",
	"TSR":"Timisoara (TSR)",
	"TOL":"Toledo (TOL)",
	"TLC":"Toluca (TLC)",
	"YTZ":"Toronto (YTZ)",
	"YYZ":"Toronto (YYZ)",
	"TRC":"Torreon (TRC)",
	"TLN":"Toulon (TLN)",
	"TLS":"Toulouse (TLS)",
	"TPS":"Trapani (TPS)",
	"TSF":"Treviso (TSF)",
	"TRS":"Trieste (TRS)",
	"TIP":"Tripoli (TIP)",
	"TOS":"Tromsø (TOS)",
	"TRD":"Trondheim (TRD)",
	"TRU":"Trujillo (TRU)",
	"TUS":"Tucson (TUS)",
	"TUC":"Tucumán (TUC)",
	"TUL":"Tulsa (TUL)",
	"TUN":"Tunes (TUN)",
	"TRN":"Turim (TRN)",
	"TKU":"Turku (TKU)",
	"TKZ":"Tuxtla Gutiérrez (TGZ)",
	"UDI":"Uberlândia (UDI)",
	"ULN":"Ulán Bator (ULN)",
	"UME":"Umeå (UME)",
	"UTN":"Upington (UTN)",
	"UPN":"Uruapan (UPN)",
	"USH":"Ushuaia (USH)",
	"VAA":"Vaasa (VAA)",
	"VLC":"Valência (VLC)",
	"VLN":"Valencia (VLN)",
	"VLL":"Valladolid (VLL)",
	"VUP":"Valledupar (VUP)",
	"YVR":"Vancouver (YVR)",
	"VRA":"Varadero (VRA)",
	"VAR":"Varna (VAR)",
	"WAW":"Varsóvia (WAW)",
	"VCE":"Veneza (VCE)",
	"VNT":"Ventspils (VNT)",
	"VER":"Veracruz (VER)",
	"VRN":"Verona (VRN)",
	"YYJ":"Victoria (YYJ)",
	"VDM":"Viedma (VDM)",
	"VIE":"Viena (VIE)",
	"VGO":"Vigo (VGO)",
	"RLO":"Villa de Merlo (RLO)",
	"VSA":"Villahermosa (VSA)",
	"VVC":"Villavicencio (VVC)",
	"VNO":"Vilnius (VNO)",
	"VIX":"Vitória (VIX)",
	"VVO":"Vladivostok (VVO)",
	"DCA":"Washington D.C. (DCA)",
	"IAD":"Washington D.C. (IAD)",
	"NRN":"Weeze (NRN)",
	"WLG":"Wellington (WLG)",
	"PBI":"West Palm Beach (PBI)",
	"HPN":"Westchester (HPN)",
	"ICT":"Wichita (ICT)",
	"AVP":"Wilkes-Barre / Scranton (AVP)",
	"ILM":"Wilmington (ILM)",
	"WDH":"Windhoek (WDH)",
	"YWG":"Winnipeg (YWG)",
	"PVG":"Xangai (PVG)",
	"SHA":"Xangai (SHA)",
	"CGK":"Yakarta (CGK)",
	"EVN":"Yerevan (EVN)",
	"EYP":"Yopal (EYP)",
	"ZAD":"Zadar (ZAD)",
	"ZAG":"Zagreb (ZAG)",
	"ZIH":"Zihuatanejo (ZIH)",
	"ILZ":"Zilina (ILZ)",
	"ZRH":"Zurique (ZRH)"
}